title:
description: ""
baseurl: ""
url: ""

# Assets
assets:
  sources:
    - node_modules
    - assets/pdf
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

# Build settings
markdown: kramdown
plugins:
  - jekyll-livereload
  - jekyll-assets

# Exclude
exclude:
  - exclude
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - CNAME # surge.sh cname
  - s3_website.yml # s3_website
