# Site settings
title: Site Title
description: "" 
baseurl: "" 
url: "http://example.com" 
exclude: [readme.md, Gemfile, Gemfile.lock, bower.json]
livereload: true

# Build settings
markdown: kramdown
gems:
  - jekyll-assets
assets:
  compress:
    css: true
    js: true
    js_compressor: uglifier
    css_compressor: sass
  autowrite: true
  sources:
    - "_assets/bower"
    - "_assets/js"
    - "_assets/css"
    - "_assets/img"
