title:
description:
baseurl: ""
url: ""
# host: localhost

# Assets
assets:
  sources:
    - node_modules
    - assets/pdf
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 11"

# Build settings
markdown: kramdown
plugins:
  - jekyll-assets
  - uglifier

# Exclude
# Exclude
exclude:
  - exclude
  - readme.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - s3_website.yml # s3_website
