title:
description:
baseurl: ""
url: ""
jquery: true

# Assets
assets:
  sources:
    - node_modules
    - assets/pdf
  autoprefixer:
    browsers:
      - "last 2 versions"

# Build settings
markdown: kramdown
plugins:
  - jekyll-assets
  - uglifier

include:
#  - _headers # Netlify headers

# Exclude
exclude:
  - exclude # use this folder to hide stuff
  - readme.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
